name: ashera_pet_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 

  accordion: ^2.6.0
  animate_icons: ^2.0.0
  bootstrap_icons: ^1.11.3
  cached_network_image: ^3.4.0
  cached_video_player_plus: ^3.0.3
  camera: ^0.11.0+1
  collection: ^1.18.0
  connectivity_plus: ^6.0.4
  dio: ^5.5.0+1
  dismissible_page: ^1.0.2
  event_bus: ^2.0.0
  expandable_bottom_sheet: ^1.1.1+1
  extended_image: ^8.1.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_cache_manager: ^3.4.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_html: ^3.0.0-beta.2
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.1+2
  flutter_native_splash: ^2.4.1
  flutter_ringtone_player: ^4.0.0+3
  flutter_slidable: ^3.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svprogresshud: ^1.0.1
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  heif_converter: ^1.0.0
  http: ^1.2.2
  image: ^4.2.0
  image_cropper: ^8.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  inview_notifier_list: ^3.0.0
  package_info_plus: ^4.2.0
  path: ^1.9.0
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  preload_page_view: ^0.2.0
  provider: ^6.1.2
  pull_to_refresh_plus: ^2.0.3
  pull_to_refresh_pro: ^0.0.1
  rf_expand_collapse_text: ^0.0.2
  screenshot: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^7.2.2
  shared_preferences: ^2.3.1
  shared_preferences_android: ^2.3.0
  shared_preferences_ios: ^2.1.1
  sqflite: ^2.3.3+1
  stomp_dart_client: ^2.0.0
  swipeable_page_route: ^0.4.3
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  video_compress: ^3.1.2
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3
  web: ^0.5.1
  web_socket_channel: ^2.4.0
  # wechat_assets_picker: ^8.8.1+1

  # 下面的東西會造成 gradlew 版本 報錯。
  # geolocator: ^13.0.0
  # google_maps_cluster_manager: ^3.1.0
  google_maps_flutter: ^2.7.1
  google_maps_flutter_platform_interface: ^2.9.0

dependency_overrides:
  scroll_to_index: ^3.0.1
  photo_manager: ^3.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/tab/
  - assets/sound/

flutter_native_splash:
  background_image: assets/images/bg.png
  web: false
  fullscreen: true
